default:
  http_metas:
    content-type: text/html

  metas:
    title:        Piwam
    description:  Gestionnaire d'association
    language:     fr

  stylesheets:    [main.css]

  javascripts:    []

  has_layout:     on
  layout:         layout
