propel:
  _attributes:   { package: lib.model }

  activite:
    _attributes:     { phpName: Activite }
    id:              ~
    libelle:         { type: varchar(255), required: true }
    actif:           { type: boolean, default: true }
    created_at:      ~
    updated_at:      ~  
  
  compte:
    _attributes:     { phpName: Compte }
    id:              ~
    libelle:         { type: varchar(255), required: true }
    reference:       { type: varchar(64), required: true }
    actif:           { type: boolean, default: true }
    created_at:      ~
    updated_at:      ~
    
  cotisation:
    _attributes:     { phpName: Cotisation }
    id:              ~
    compte_id:       { type: integer, required: true, foreignTable: compte, foreignReference: id, onDelete: setnull }
    cotisation_type_id:   { type: integer, required: true, foreignTable: cotisation_type, foreignReference: id, onDelete: setnull }
    membre_id:       { type: integer, required: true }
    date:            { type: date, required: true }
    created_at:      ~
    updated_at:      ~
    
  cotisation_type:
    _attributes:     { phpName: CotisationType }
    id:              ~
    libelle:         { type: varchar(255), required: true }
    valide:          { type: integer, required: true }
    montant:         { type: decimal, required: true }
    actif:           { type: boolean, default: true }
    created_at:      ~
    updated_at:      ~
    
  depense:
    _attributes:     { phpName: Depense }
    id:              ~
    libelle:         { type: varchar(255), required: true }
    montant:         { type: decimal, required: true }
    compte_id:       { type: integer, required: true, foreignTable: compte, foreignReference: id, onDelete: setnull }
    activite_id:     { type: integer, required: true, foreignTable: activite, foreignReference: id, onDelete: setnull }
    date:            { type: date, required: true }
    created_at:      ~
    updated_at:      ~
  
  membre:
    _attributes:     { phpName: Membre }
    id:              ~
    nom:             { type: varchar(255), required: true }
    prenom:          { type: varchar(255), required: true }
    pseudo:          { type: varchar(255), required: true }
    password:        { type: varchar(255), required: true }
    statut_id:       { type: integer, required: true, foreignTable: statut, foreignReference: id, onDelete: setnull }
    dateInscription: { type: date, required: true }
    exempteCotis:    { type: boolean, required: true }
    rue:             { type: varchar(255) }
    cp:              { type: varchar(8) }
    ville:           { type: varchar(255) }
    pays:            { type: varchar(8) }
    email:           { type: varchar(255) }
    website:         { type: varchar(255) }
    telFixe:         { type: varchar(16) }
    telPortable:     { type: varchar(16) }
    actif:           { type: boolean, default: true }
    created_at:      ~
    updated_at:      ~
    
  recette:
    _attributes:     { phpName: Recette }
    id:              ~
    libelle:         { type: varchar(255), required: true }
    montant:         { type: decimal, required: true }
    compte_id:       { type: integer, required: true, foreignTable: compte, foreignReference: id, onDelete: setnull }
    activite_id:     { type: integer, required: true, foreignTable: activite, foreignReference: id, onDelete: setnull }
    date:            { type: date, required: true }
    created_at:      ~
    updated_at:      ~
    
  statut:
    _attributes:     { phpName: Statut }
    id:              ~
    nom:             { type: varchar(255), required: true }
    actif:           { type: boolean, default: true }
    created_at:      ~
    updated_at:      ~
